project:
  type: website

website:
  title: "quarto-site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: fred-data-pipeline.qmd
        text: FRED Data Pipeline

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    code-fold: true



